version: '3'

services:
  database:
    image: mongo
    container_name: mongodb-container
    env_file:
      - .env
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DB}
      MONGO_USERNAME: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  app:
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MIX_DEV=dev
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "80:80"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MIX_ENV=dev
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: >
      sh -c "npm install && npx nodemon index.js"
